#!/usr/bin/env node
/**
 * AI Agent Academy — Agent Builder
 * No-code: chat prompt → agent template → Antigravity workspace deploy
 * Supports Gemini 3 Pro / Ollama autodetect
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { execSync, spawn } = require('child_process');

// ─── Config ──────────────────────────────────────────────────────────────────

const DIST_DIR = path.join(__dirname, '..', 'dist');
const TEMPLATES_DIR = path.join(__dirname, 'agent-templates');
const ANTIGRAVITY_BRIDGE = path.join(__dirname, 'antigravity-bridge', 'mcp-server.js');

const CONFIG = {
  antigravityHost: process.env.ANTIGRAVITY_HOST || 'http://localhost:3000',
  geminiApiKey: process.env.GEMINI_API_KEY || null,
  ollamaHost: process.env.OLLAMA_HOST || 'http://localhost:11434',
  deployTimeout: 90_000, // 90 seconds
};

// ─── Utilities ────────────────────────────────────────────────────────────────

function log(msg, level = 'info') {
  const icons = { info: '🚀', success: '✅', warn: '⚠️ ', error: '❌', agent: '🤖' };
  console.log(`${icons[level] || '•'} [Academy] ${msg}`);
}

function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
    log(`Created directory: ${dir}`);
  }
}

// ─── Model Autodetect ─────────────────────────────────────────────────────────

async function detectModel() {
  if (CONFIG.geminiApiKey) {
    log('Gemini 3 Pro detected via GEMINI_API_KEY', 'success');
    return { provider: 'gemini', model: 'gemini-3-pro' };
  }

  try {
    const http = require('http');
    await new Promise((resolve, reject) => {
      const req = http.get(`${CONFIG.ollamaHost}/api/tags`, (res) => {
        if (res.statusCode === 200) resolve();
        else reject(new Error(`Ollama returned ${res.statusCode}`));
      });
      req.on('error', reject);
      req.setTimeout(2000, () => { req.destroy(); reject(new Error('timeout')); });
    });
    log('Ollama local model detected (fallback)', 'success');
    return { provider: 'ollama', model: 'llama3' };
  } catch {
    log('No model provider detected — running in template-only mode', 'warn');
    return { provider: 'template', model: 'none' };
  }
}

// ─── Agent Generation ─────────────────────────────────────────────────────────

/**
 * Generate agent code from a prompt using Gemini or Ollama
 */
async function generateAgentCode(prompt, modelInfo) {
  const systemPrompt = `You are an expert AI agent developer. Generate a complete, production-ready Node.js agent script based on the user's description. The agent should:
- Be self-contained and runnable with node agent.js
- Include error handling
- Log its actions clearly
- Be deployable to Antigravity workspaces
Return ONLY the JavaScript code, no markdown fences.`;

  if (modelInfo.provider === 'gemini') {
    const { GoogleGenerativeAI } = require('@google/generative-ai');
    const genAI = new GoogleGenerativeAI(CONFIG.geminiApiKey);
    const model = genAI.getGenerativeModel({ model: 'gemini-pro' });
    const result = await model.generateContent(`${systemPrompt}\n\nUser request: ${prompt}`);
    return result.response.text();
  }

  if (modelInfo.provider === 'ollama') {
    const http = require('http');
    return new Promise((resolve, reject) => {
      const body = JSON.stringify({
        model: modelInfo.model,
        prompt: `${systemPrompt}\n\nUser request: ${prompt}`,
        stream: false,
      });
      const req = http.request(
        `${CONFIG.ollamaHost}/api/generate`,
        { method: 'POST', headers: { 'Content-Type': 'application/json' } },
        (res) => {
          let data = '';
          res.on('data', (chunk) => (data += chunk));
          res.on('end', () => {
            try {
              resolve(JSON.parse(data).response);
            } catch {
              reject(new Error('Failed to parse Ollama response'));
            }
          });
        }
      );
      req.on('error', reject);
      req.write(body);
      req.end();
    });
  }

  // Template-only fallback
  return loadTemplate('research').replace('{{PROMPT}}', prompt);
}

// ─── Template Loader ──────────────────────────────────────────────────────────

function loadTemplate(type = 'research') {
  const templatePath = path.join(TEMPLATES_DIR, `${type}.js`);
  if (fs.existsSync(templatePath)) {
    return fs.readFileSync(templatePath, 'utf8');
  }
  // Inline fallback template
  return `#!/usr/bin/env node
// Auto-generated agent: {{PROMPT}}
// Generated by AI Agent Academy v4.0

const task = process.argv[2] || '{{PROMPT}}';

async function run() {
  console.log('🤖 Agent starting task:', task);
  console.log('📡 Connecting to Antigravity workspace...');
  
  // TODO: Replace with actual agent logic
  await new Promise(r => setTimeout(r, 1000));
  
  console.log('✅ Agent task complete:', task);
}

run().catch(console.error);
`;
}

// ─── Antigravity Deploy ───────────────────────────────────────────────────────

async function deployToAntigravity(agentPath) {
  log(`Deploying ${agentPath} to Antigravity workspace...`);

  // Check if Antigravity bridge is running
  try {
    const http = require('http');
    await new Promise((resolve, reject) => {
      const req = http.get(`${CONFIG.antigravityHost}/health`, (res) => {
        if (res.statusCode === 200) resolve();
        else reject(new Error(`Bridge returned ${res.statusCode}`));
      });
      req.on('error', reject);
      req.setTimeout(3000, () => { req.destroy(); reject(new Error('timeout')); });
    });

    // Deploy via MCP bridge
    const http = require('http');
    const agentCode = fs.readFileSync(agentPath, 'utf8');
    const body = JSON.stringify({
      action: 'deploy',
      agent: { path: agentPath, code: agentCode },
      workspace: process.env.ANTIGRAVITY_WORKSPACE || 'default',
    });

    await new Promise((resolve, reject) => {
      const req = http.request(
        `${CONFIG.antigravityHost}/mcp/v1/deploy`,
        { method: 'POST', headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(body) } },
        (res) => {
          let data = '';
          res.on('data', (chunk) => (data += chunk));
          res.on('end', () => {
            log(`Antigravity deploy response: ${data}`, 'success');
            resolve();
          });
        }
      );
      req.on('error', reject);
      req.write(body);
      req.end();
    });

    log('Agent deployed to Antigravity in <90s! 🎉', 'success');
  } catch (err) {
    log(`Antigravity bridge not reachable (${err.message}) — agent saved locally at ${agentPath}`, 'warn');
    log('Run `npm run antigravity` to start the bridge, then redeploy', 'info');
  }
}

// ─── Main: buildAgent ─────────────────────────────────────────────────────────

async function buildAgent(prompt) {
  if (!prompt) {
    log('Usage: node src/agent-builder.js "<your agent description>"', 'warn');
    log('Example: node src/agent-builder.js "research agent that summarizes arXiv papers"', 'info');
    printWelcome();
    return;
  }

  log(`Building agent for: "${prompt}"`, 'agent');

  ensureDir(DIST_DIR);

  // 1. Detect model provider
  const modelInfo = await detectModel();
  log(`Using model: ${modelInfo.provider}/${modelInfo.model}`);

  // 2. Generate agent code
  log('Generating agent code...');
  let agentCode;
  try {
    agentCode = await generateAgentCode(prompt, modelInfo);
  } catch (err) {
    log(`Code generation failed: ${err.message} — using template fallback`, 'warn');
    agentCode = loadTemplate('research').replace(/\{\{PROMPT\}\}/g, prompt);
  }

  // 3. Write to dist/
  const agentName = prompt
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .slice(0, 40);
  const agentPath = path.join(DIST_DIR, `agent-${agentName}.js`);
  fs.writeFileSync(agentPath, agentCode);
  log(`Agent written to: ${agentPath}`, 'success');

  // 4. Deploy to Antigravity
  await deployToAntigravity(agentPath);

  return agentPath;
}

// ─── Welcome Banner ───────────────────────────────────────────────────────────

function printWelcome() {
  console.log(`
╔══════════════════════════════════════════════════════════════╗
║        🚀 AI Agent Academy + Antigravity Launcher v4.0       ║
╠══════════════════════════════════════════════════════════════╣
║  Commands:                                                    ║
║  npm run academy          → Interactive agent builder         ║
║  npm run antigravity      → Start MCP bridge server           ║
║  npm run swarm            → Launch swarm orchestrator         ║
║  npm run no-code          → Chat-to-agent (no-code mode)      ║
║  npm run marketplace:publish → Publish to marketplace         ║
║  npm run teach            → View tutorials                    ║
╠══════════════════════════════════════════════════════════════╣
║  Quick start:                                                 ║
║  node src/agent-builder.js "research agent for arXiv"        ║
╚══════════════════════════════════════════════════════════════╝
`);
}

// ─── Entry Point ──────────────────────────────────────────────────────────────

if (require.main === module) {
  const prompt = process.argv.slice(2).join(' ');
  buildAgent(prompt).catch((err) => {
    log(`Fatal error: ${err.message}`, 'error');
    process.exit(1);
  });
}

module.exports = { buildAgent, detectModel, loadTemplate, generateAgentCode };
