#!/usr/bin/env node
/**
 * AI Agent Builder - Lightweight wrapper for Next.js template
 * No external dependencies - uses template fallback mode
 */

const fs = require('fs');
const path = require('path');

const DIST_DIR = path.join(process.cwd(), 'agents');

function log(msg, icon = '•') {
  console.log(`${icon} ${msg}`);
}

function ensureDir(dir) {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
}

function generateAgentLogic(prompt) {
  const patterns = [
    { test: /research|arxiv|paper/i, log: '🔬 Research task detected', hint: 'Add fetch/axios to pull papers' },
    { test: /monitor|track|watch/i, log: '👁️  Monitor task detected', hint: 'Add cron or interval polling' },
    { test: /analyze|analysis/i, log: '📊 Analysis task detected', hint: 'Add data processing logic' },
    { test: /generate|create|build/i, log: '🏗️  Generation task detected', hint: 'Add file/output creation' },
  ];
  
  for (const { test, log, hint } of patterns) {
    if (test.test(prompt)) {
      return `console.log('${log}');\n  console.log('💡 Hint: ${hint}');`;
    }
  }
  return "console.log('🔧 General task mode');";
}

function templateAgent(prompt) {
  const logic = generateAgentLogic(prompt);
  return `#!/usr/bin/env node
// Auto-generated agent: ${prompt}
// Generated by AI Agent Academy v4.0 (template mode)

const task = process.argv[2] || '${prompt}';

async function run() {
  console.log('🤖 Agent starting task:', task);
  console.log('📝 Description:', '${prompt}');
  ${logic}
  console.log('✅ Agent task complete');
}

run().catch(console.error);
`;
}

async function buildAgent(prompt) {
  if (!prompt) {
    console.log(`
📋 AI Agent Builder (Template Mode)
────────────────────────────────────
Usage: node scripts/agent.js "<agent description>"

Examples:
  node scripts/agent.js "research agent that summarizes arXiv papers"
  node scripts/agent.js "monitor GitHub for new AI repos"
  node scripts/agent.js "analyze CSV data and generate report"

To unlock full AI generation with Gemini/Ollama, install:
  cd ai-agent-academy-antigravity-v4.0 && npm install
`);
    return;
  }

  log('Building agent for: "' + prompt + '"', '🤖');
  
  ensureDir(DIST_DIR);
  
  const agentName = prompt.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 40);
  const agentPath = path.join(DIST_DIR, `agent-${agentName}.js`);
  
  const code = templateAgent(prompt);
  fs.writeFileSync(agentPath, code);
  
  log(`Agent written to: ${agentPath}`, '✅');
  log(`Run with: node ${agentPath}`, '▶');
}

buildAgent(process.argv.slice(2).join(' ')).catch(console.error);